baseURL = "https://mandirasharma.com.np/"
languageCode = "en-us"
title = "Mandira Sharma"

[params]
  description = "Mandira Sharma — AI/ML & Software Engineering"

[build]
  writeStats = false

[minify]
  disableXML = true
